const conflictosPorPais = {
    "Croatia": 2,
    "China": 24,
    "Vietnam": 14,
    "Indonesia": 18,
    "North Korea": 4,
    "South Korea": 10,
    "Afghanistan": 17,
    "Iran": 21,
    "Greece": 4,
    "Philippines": 9,
    "Albania": 3,
    "India": 25,
    "Laos": 5,
    "Cambodia": 7,
    "Paraguay": 6,
    "Madagascar": 2,
    "Pakistan": 17,
    "Romania": 3,
    "Israel": 9,
    "Palestine": 15,
    "Jordan": 5,
    "Iraq": 25,
    "Myanmar": 3,
    "Colombia": 3,
    "Malaysia": 7,
    "Singapore": 1,
    "Thailand": 6,
    "United States": 1,
    "Oman": 7,
    "United Arab Emirates": 2,
    "Egypt": 8,
    "Kenya": 2,
    "Czech Republic": 5,
    "Germany": 2,
    "Cuba": 6,
    "Kazakhstan": 2,
    "Taiwan": 4,
    "Algeria": 6,
    "Costa Rica": 3,
    "Cameroon": 4,
    "South Sudan": 4,
    "Cyprus": 2,
    "Hungary": 2,
    "Poland": 2,
    "Morocco": 5,
    "Lebanon": 11,
    "Guatemala": 3,
    "Mexico": 8,
    "Panama": 2,
    "East Timor": 6,
    "Spain": 2,
    "France": 3,
    "Republic of the Congo": 6,
    "Ethiopia": 21,
    "Angola": 4,
    "Nicaragua": 2,
    "Tunisia": 5,
    "Eritrea": 4,
    "Dominican Republic": 6,
    "Somalia": 9,
    "Mali": 2,
    "Venezuela": 6,
    "Argentina": 2,
    "Yemen": 15,
    "Papua New Guinea": 4,
    "Brunei": 2,
    "Democratic Republic of the Congo": 19,
    "Guinea-Bissau": 3,
    "Syria": 14,
    "Tanzania": 2,
    "Brazil": 5,
    "Zimbabwe": 2,
    "Mozambique": 3,
    "Chad": 5,
    "Namibia": 3,
    "Bolivia": 4,
    "Nigeria": 7,
    "Northern Ireland": 2,
    "Italy": 4,
    "Guyana": 2,
    "El Salvador": 4,
    "Uganda": 10,
    "Sri Lanka": 8,
    "Saudi Arabia": 5,
    "Bangladesh": 8,
    "Turkey": 6,
    "Kuwait": 2,
    "Chile": 4,
    "Peru": 3,
    "Gambia": 2,
    "Senegal": 2,
    "Puerto Rico": 1,
    "Somaliland": 2,
    "Russia": 15,
    "Sudan": 8,
    "Falkland Islands": 1,
    "Sierra Leone": 2,
    "Grenada": 1,
    "Libya": 5,
    "Suriname": 1,
    "South Africa": 2,
    "Bhutan": 1,
    "Estonia": 1,
    "Azerbaijan": 6,
    "Maldives": 1,
    "Liberia": 3,
    "Rwanda": 1,
    "Moldova": 1,
    "Georgia": 5,
    "Bosnia and Herzegovina": 2,
    "Slovenia": 1,
    "Djibouti": 2,
    "Tajikistan": 3,
    "Burundi": 1,
    "Nepal": 1,
    "Kosovo": 2,
    "Serbia": 2,
    "Kyrgyzstan": 4,
    "North Macedonia": 1,
    "Qatar": 1,
    "Ivory Coast": 2,
    "Central African Republic": 1,
    "Niger": 2,
    "Saada": 1,
    "Jamaica": 1,
    "Bahrain": 1,
    "Armenia": 3,
    "Haiti": 1,
    "Togo": 1,
    "Burma": 1,
    "Ecuador": 1
};
